# creating a matrix

In [1]:
vec = 1:10
print(vec)

 [1]  1  2  3  4  5  6  7  8  9 10


In [3]:
print(matrix(vec))

      [,1]
 [1,]    1
 [2,]    2
 [3,]    3
 [4,]    4
 [5,]    5
 [6,]    6
 [7,]    7
 [8,]    8
 [9,]    9
[10,]   10


In [6]:
print(matrix(vec, nrow=2))

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10


In [8]:
print(matrix(1:12, nrow=4, byrow=FALSE))

     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12


In [9]:
print(matrix(1:12, nrow=4, byrow=TRUE))

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9
[4,]   10   11   12


In [10]:
goog <- c(450, 451, 452, 445, 468)
msft <- c(230, 232, 235, 240, 250)
stocks <- c(goog, msft)

print(stocks)

 [1] 450 451 452 445 468 230 232 235 240 250


In [12]:
# build a matrix
stock.matrix <- matrix(stocks, byrow=TRUE, nrow=2)
print(stock.matrix)

     [,1] [,2] [,3] [,4] [,5]
[1,]  450  451  452  445  468
[2,]  230  232  235  240  250


In [13]:
days <- c("Mon", "Tue", "Wed", "Thu", "Fri")
stock.names <- c("GOOG", "MSFT")

colnames(stock.matrix) <- days
rownames(stock.matrix) <- stock.names

print(stock.matrix)

     Mon Tue Wed Thu Fri
GOOG 450 451 452 445 468
MSFT 230 232 235 240 250


# matrix arithmetic:

In [14]:
mat <- matrix(1:25, nrow=5, byrow=TRUE)
print(mat)

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    2    3    4    5
[2,]    6    7    8    9   10
[3,]   11   12   13   14   15
[4,]   16   17   18   19   20
[5,]   21   22   23   24   25


In [16]:
print(mat+2)

     [,1] [,2] [,3] [,4] [,5]
[1,]    3    4    5    6    7
[2,]    8    9   10   11   12
[3,]   13   14   15   16   17
[4,]   18   19   20   21   22
[5,]   23   24   25   26   27


In [17]:
print(mat-2)

     [,1] [,2] [,3] [,4] [,5]
[1,]   -1    0    1    2    3
[2,]    4    5    6    7    8
[3,]    9   10   11   12   13
[4,]   14   15   16   17   18
[5,]   19   20   21   22   23


In [18]:
print(mat^2)

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    4    9   16   25
[2,]   36   49   64   81  100
[3,]  121  144  169  196  225
[4,]  256  289  324  361  400
[5,]  441  484  529  576  625


In [19]:
print(mat%%10)

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    2    3    4    5
[2,]    6    7    8    9    0
[3,]    1    2    3    4    5
[4,]    6    7    8    9    0
[5,]    1    2    3    4    5


In [20]:
print(1/mat)

           [,1]       [,2]       [,3]       [,4]       [,5]
[1,] 1.00000000 0.50000000 0.33333333 0.25000000 0.20000000
[2,] 0.16666667 0.14285714 0.12500000 0.11111111 0.10000000
[3,] 0.09090909 0.08333333 0.07692308 0.07142857 0.06666667
[4,] 0.06250000 0.05882353 0.05555556 0.05263158 0.05000000
[5,] 0.04761905 0.04545455 0.04347826 0.04166667 0.04000000


In [21]:
print(mat > 15)

      [,1]  [,2]  [,3]  [,4]  [,5]
[1,] FALSE FALSE FALSE FALSE FALSE
[2,] FALSE FALSE FALSE FALSE FALSE
[3,] FALSE FALSE FALSE FALSE FALSE
[4,]  TRUE  TRUE  TRUE  TRUE  TRUE
[5,]  TRUE  TRUE  TRUE  TRUE  TRUE


In [22]:
print(mat[mat>15])

 [1] 16 21 17 22 18 23 19 24 20 25


In [23]:
print(mat * mat)

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    4    9   16   25
[2,]   36   49   64   81  100
[3,]  121  144  169  196  225
[4,]  256  289  324  361  400
[5,]  441  484  529  576  625


In [24]:
print(mat ^ mat)

             [,1]         [,2]         [,3]         [,4]         [,5]
[1,] 1.000000e+00 4.000000e+00 2.700000e+01 2.560000e+02 3.125000e+03
[2,] 4.665600e+04 8.235430e+05 1.677722e+07 3.874205e+08 1.000000e+10
[3,] 2.853117e+11 8.916100e+12 3.028751e+14 1.111201e+16 4.378939e+17
[4,] 1.844674e+19 8.272403e+20 3.934641e+22 1.978420e+24 1.048576e+26
[5,] 5.842587e+27 3.414279e+29 2.088047e+31 1.333736e+33 8.881784e+34


In [26]:
mat %% mat

[,1] [,2] [,3] [,4] [,5]
[1,] 0    0    0    0    0   
[2,] 0    0    0    0    0   
[3,] 0    0    0    0    0   
[4,] 0    0    0    0    0   
[5,] 0    0    0    0    0

# matrix operations

In [29]:
goog <- c(450, 451, 452, 445, 468)
msft <- c(230, 232, 235, 240, 250)

stocks <- c(goog, msft)
stock.matrix <- matrix(stocks, byrow=TRUE, nrow=2)

days <- c("Mon", "Tue", "Wed", "Thu", "Fri")
stock.names <- c("GOOG", "MSFT")

colnames(stock.matrix) <- days
rownames(stock.matrix) <- stock.names

print(stock.matrix)

     Mon Tue Wed Thu Fri
GOOG 450 451 452 445 468
MSFT 230 232 235 240 250


In [32]:
# sum the columns
print(colSums(stock.matrix))

Mon Tue Wed Thu Fri 
680 683 687 685 718 


In [33]:
# sum the rows
print(rowSums(stock.matrix))

GOOG MSFT 
2266 1187 


In [34]:
print(rowMeans(stock.matrix))

 GOOG  MSFT 
453.2 237.4 


In [35]:
print(colMeans(stock.matrix))

  Mon   Tue   Wed   Thu   Fri 
340.0 341.5 343.5 342.5 359.0 


add columns and rows to a matrix

In [38]:
FB <- c(111, 112, 113, 120, 145)

In [39]:
tech.stocks <- rbind(stock.matrix, FB)
print(tech.stocks)

     Mon Tue Wed Thu Fri
GOOG 450 451 452 445 468
MSFT 230 232 235 240 250
FB   111 112 113 120 145


In [40]:
avg <- rowMeans(tech.stocks)

In [41]:
print(avg)

 GOOG  MSFT    FB 
453.2 237.4 120.2 


In [42]:
tech.stocks <- cbind(tech.stocks, avg)

In [43]:
print(tech.stocks)

     Mon Tue Wed Thu Fri   avg
GOOG 450 451 452 445 468 453.2
MSFT 230 232 235 240 250 237.4
FB   111 112 113 120 145 120.2


# matrix selection and indexing

In [44]:
mat <- matrix(1:50, nrow=5, byrow=TRUE)
print(mat)

     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]    1    2    3    4    5    6    7    8    9    10
[2,]   11   12   13   14   15   16   17   18   19    20
[3,]   21   22   23   24   25   26   27   28   29    30
[4,]   31   32   33   34   35   36   37   38   39    40
[5,]   41   42   43   44   45   46   47   48   49    50


In [45]:
# get first row
print(mat[1,])

 [1]  1  2  3  4  5  6  7  8  9 10


In [46]:
# get first column
print(mat[,1])

[1]  1 11 21 31 41


In [50]:
# get first three rows
print(mat[1:3,])

     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]    1    2    3    4    5    6    7    8    9    10
[2,]   11   12   13   14   15   16   17   18   19    20
[3,]   21   22   23   24   25   26   27   28   29    30


In [51]:
print(mat)

     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]    1    2    3    4    5    6    7    8    9    10
[2,]   11   12   13   14   15   16   17   18   19    20
[3,]   21   22   23   24   25   26   27   28   29    30
[4,]   31   32   33   34   35   36   37   38   39    40
[5,]   41   42   43   44   45   46   47   48   49    50


In [52]:
print(mat[,1:3])

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]   11   12   13
[3,]   21   22   23
[4,]   31   32   33
[5,]   41   42   43


In [54]:
print(mat[1:2, 1:3])

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]   11   12   13


In [57]:
print(mat[3:4, 7:10])

     [,1] [,2] [,3] [,4]
[1,]   27   28   29   30
[2,]   37   38   39   40


In [58]:
print(mat)

     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]    1    2    3    4    5    6    7    8    9    10
[2,]   11   12   13   14   15   16   17   18   19    20
[3,]   21   22   23   24   25   26   27   28   29    30
[4,]   31   32   33   34   35   36   37   38   39    40
[5,]   41   42   43   44   45   46   47   48   49    50


In [59]:
print(mat[2:3, 5:6])

     [,1] [,2]
[1,]   15   16
[2,]   25   26


In [61]:
print(mat[3:5, 7:10])

     [,1] [,2] [,3] [,4]
[1,]   27   28   29   30
[2,]   37   38   39   40
[3,]   47   48   49   50


# factor and categorcal matrix

In [62]:
animal <- c("cat", "dog", "dog", "cat", "cat")
id <- c(1, 2, 3, 4, 5)

In [64]:
print(factor(animal))

[1] cat dog dog cat cat
Levels: cat dog


In [65]:
fact.ani <- factor(animal)
print(fact.ani)

[1] cat dog dog cat cat
Levels: cat dog


In [66]:
# nominal categorical variables have no order
# ordinal categorical variables have order

In [67]:
ordinal.cat <- c("low", "medium", "high")


In [68]:
temperatures <- c('cold', 'medium', 'hot', 'hot', 'hot', 'cold', 'medium')

In [69]:
print(ordinal.cat)

[1] "low"    "medium" "high"  


In [70]:
print(temperatures)

[1] "cold"   "medium" "hot"    "hot"    "hot"    "cold"   "medium"


In [74]:
fact.temp <- factor(temperatures, ordered=TRUE, levels=c("cold", "medium", "hot"))
print(fact.temp)

[1] cold   medium hot    hot    hot    cold   medium
Levels: cold < medium < hot


In [76]:
print(summary(fact.temp))


  cold medium    hot 
     2      2      3 
