In [3]:
A <- 1:3
B <- 4:6
mat <- rbind(A, B)

In [4]:
print(mat)

  [,1] [,2] [,3]
A    1    2    3
B    4    5    6


In [22]:
mat = matrix(1:9, nrow=3, byrow=TRUE)
print(mat)

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9


In [6]:
print(is.matrix(mat))

[1] TRUE


In [8]:
mat.25 <- matrix(1:25, nrow=5, byrow=TRUE)
print(mat.25)

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    2    3    4    5
[2,]    6    7    8    9   10
[3,]   11   12   13   14   15
[4,]   16   17   18   19   20
[5,]   21   22   23   24   25


In [9]:
print(mat.25[2:3, 2:3])

     [,1] [,2]
[1,]    7    8
[2,]   12   13


In [10]:
print(mat.25[4:5, 4:5])

     [,1] [,2]
[1,]   19   20
[2,]   24   25


In [14]:
print(sum(mat.25))

[1] 325


In [15]:
help(runif)

Warning message in seq_len(head.end.idx):
"first element used of 'length.out' argument"
ERROR while rich displaying an object: Error in seq_len(head.end.idx): argument must be coercible to non-negative integer

Traceback:
1. FUN(X[[i]], ...)
2. tryCatch(withCallingHandlers({
 .     if (!mime %in% names(repr::mime2repr)) 
 .         stop("No repr_* for mimetype ", mime, " in repr::mime2repr")
 .     rpr <- repr::mime2repr[[mime]](obj)
 .     if (is.null(rpr)) 
 .         return(NULL)
 .     prepare_content(is.raw(rpr), rpr)
 . }, error = error_handler), error = outer_handler)
3. tryCatchList(expr, classes, parentenv, handlers)
4. tryCatchOne(expr, names, parentenv, handlers[[1L]])
5. doTryCatch(return(expr), name, parentenv, handler)
6. withCallingHandlers({
 .     if (!mime %in% names(repr::mime2repr)) 
 .         stop("No repr_* for mimetype ", mime, " in repr::mime2repr")
 .     rpr <- repr::mime2repr[[mime]](obj)
 .     if (is.null(rpr)) 
 .         return(NULL)
 .     prepare_conte

Uniform                 package:stats                  R Documentation

_T_h_e _U_n_i_f_o_r_m _D_i_s_t_r_i_b_u_t_i_o_n

_D_e_s_c_r_i_p_t_i_o_n:

     These functions provide information about the uniform distribution
     on the interval from 'min' to 'max'.  'dunif' gives the density,
     'punif' gives the distribution function 'qunif' gives the quantile
     function and 'runif' generates random deviates.

_U_s_a_g_e:

     dunif(x, min = 0, max = 1, log = FALSE)
     punif(q, min = 0, max = 1, lower.tail = TRUE, log.p = FALSE)
     qunif(p, min = 0, max = 1, lower.tail = TRUE, log.p = FALSE)
     runif(n, min = 0, max = 1)
     
_A_r_g_u_m_e_n_t_s:

    x, q: vector of quantiles.

       p: vector of probabilities.

       n: number of observations. If 'length(n) > 1', the length is
          taken to be the number required.

min, max: lower and upper limits of the distribution.  Must be finite.

log, log.p: logical; if TRUE, probabili

In [24]:
mat.20 <- matrix(runif(20, min=0, max=100), nrow=4, ncol=5)
print(mat.20)

         [,1]     [,2]     [,3]     [,4]     [,5]
[1,] 15.69480 15.67296 36.03026 92.89566 33.74047
[2,] 83.15929 61.20487 25.47281 19.41453 92.02792
[3,] 21.77527 49.13122 15.17207 79.79449 85.51607
[4,] 82.97393 17.47842 88.74747 35.64993 29.91076
